### ISSUE TITLE
267bd2f6ea2d4ecfb0adc614b31bc6c74f770777

### ISSUE THREAD

**Issue by abirfo** [tighten/tlint#363]
```[tasklist]
### Tasks
- [ ] https://github.com/tighten/tlint/issues/357
- [ ] https://github.com/tighten/tlint/issues/106
- [ ] https://github.com/tighten/tlint/issues/360
- [ ] https://github.com/tighten/tlint/pull/362
- [ ] https://github.com/tighten/tlint/issues/352
```
