### ISSUE TITLE
https://packagecontrol.io/packages/SublimeLinter-contrib-tlint

### ISSUE THREAD

**Issue by abirfo** [tighten/tlint#364]
```[tasklist]
### Tasks
- [ ] https://github.com/tighten/tlint/issues/363
- [ ] https://github.com/tighten/tlint/issues/106
- [ ] https://github.com/tighten/tlint/issues/357
- [ ] https://github.com/tighten/tlint/issues/359
- [ ] https://github.com/tighten/tlint/issues/360
- [ ] https://github.com/tighten/tlint/pull/362
- [ ] https://github.com/tighten/tlint/issues/352
- [ ] https://github.com/tighten/tlint/issues/356
- [ ] https://github.com/tighten/tlint/pull/358
- [ ] https://github.com/tighten/tlint/pull/354
- [ ] https://github.com/tighten/tlint/pull/353
- [ ] https://github.com/tighten/tlint/issues/349
- [ ] https://github.com/tighten/tlint/pull/351
- [ ] https://github.com/tighten/tlint/pull/350
- [ ] https://github.com/tighten/tlint/pull/348
- [ ] https://github.com/tighten/tlint/issues/345
- [ ] https://github.com/tighten/tlint/issues/324
- [ ] https://github.com/tighten/tlint/pull/343
- [ ] https://github.com/tighten/tlint/pull/344
- [ ] https://github.com/tighten/tlint/pull/347
- [ ] Hh
```
